package com.generate.invoice.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;

import org.hibernate.annotations.ColumnDefault;

import com.generate.invoice.entity.info.AutoGeneratedId;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.FieldDefaults;

/**
 *
 * @author manish
 */
@Getter
@Setter
@MappedSuperclass
@FieldDefaults(level = AccessLevel.PRIVATE)
public class BaseEntity implements AutoGeneratedId, Serializable {

	public static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	Long id;

	@Column(name = "created_on")
	LocalDateTime createdOn;

	@Column(name = "updated_on")
	LocalDateTime updatedOn;

	@Column(name = "deleted")
	@ColumnDefault(value = "0")
	Boolean deleted = false;

	@Column(name = "active")
	@ColumnDefault(value = "1")
	Boolean active = true;
	
	
	@PrePersist
	public void prePersist() {
		if (createdOn == null) {
			createdOn = LocalDateTime.now();
			
		}
	}

	@PreUpdate
	public void preUpdate() {
		
		updatedOn = LocalDateTime.now();
	}

}